"""Contrato común de las pantallas de la aplicación."""
from typing import Protocol


class Escena(Protocol):
    def procesarEvento(self, evento) -> None: ...
    def actualizar(self, deltaTiempo: float) -> None: ...
    def dibujar(self) -> None: ...
    def cerrar(self) -> None: ...
